[package]
name = "lightborne"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["dynamic_linking"] }
bevy_ecs_ldtk = { version = "0.11.0", path = "external/bevy_ecs_ldtk"}
bevy_rapier2d = "0.28.0"
enum-map = "2.7.3"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

